// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlI97v9va7ZOiJlLGjHB6APLzWZjMMb6s',
    appId: '1:689508132473:web:971836f98a0bd180ad56a8',
    messagingSenderId: '689508132473',
    projectId: 'campominado-30382',
    authDomain: 'campominado-30382.firebaseapp.com',
    storageBucket: 'campominado-30382.appspot.com',
    measurementId: 'G-LGEXYBNTC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtp3OkwF6Eme4NdMAUQgJsy5gY6JRCdH0',
    appId: '1:689508132473:android:920778f1f094af0bad56a8',
    messagingSenderId: '689508132473',
    projectId: 'campominado-30382',
    storageBucket: 'campominado-30382.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDXGpClyvOplISyW9V9iIPyPRiyNcsLhQ',
    appId: '1:689508132473:ios:31b9531b3adc1995ad56a8',
    messagingSenderId: '689508132473',
    projectId: 'campominado-30382',
    storageBucket: 'campominado-30382.appspot.com',
    iosBundleId: 'com.example.campo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDXGpClyvOplISyW9V9iIPyPRiyNcsLhQ',
    appId: '1:689508132473:ios:833dbc103808c0f7ad56a8',
    messagingSenderId: '689508132473',
    projectId: 'campominado-30382',
    storageBucket: 'campominado-30382.appspot.com',
    iosBundleId: 'com.example.campo.RunnerTests',
  );
}
